perf-tool: fix process crashes.
eclipse/openj9-utils pull request #54
Opened 2021-03-22 10:10 UTC by PoojaDurgad

avoid process crashes for non-existent command file.
fixes: https://github.com/eclipse/openj9-utils/issues/33

Signed-off-by: PoojaDurgad <Pooja.D.P@ibm.com>

2021-03-22 12:35 UTC, PoojaDurgad commented
@mpirvu - pls review

2021-03-22 12:57 UTC, mpirvu requested changes

2021-03-22 12:57 UTC, mpirvu commented on perf-tool/src/agent.cpp
> +
Since in OpenJ9 we avoid using streams, let's use the traditional C way of determining whether the file exists (fopen/fclose)

2021-03-22 12:57 UTC, mpirvu commented on perf-tool/src/agent.cpp
> +
Also, since this is an usage error, maybe we should print the message to stderr.

2021-03-22 12:57 UTC, mpirvu commented on perf-tool/src/agent.cpp
> +
Also, you do not need two printf statements. One is enough. 
Typo: "doesn't exists" --> "doesn't exist"

2021-03-22 13:40 UTC, PoojaDurgad commented
@mpirvu - PTAL

2021-03-22 14:44 UTC, mpirvu commented on perf-tool/src/agent.cpp
> +    fprintf(stderr, "doesn't exist\n");
The message should specify what does not exist.

2021-03-22 15:10 UTC, PoojaDurgad commented
@mpirvu - PTAL

2021-03-22 15:31 UTC, mpirvu commented on perf-tool/src/agent.cpp
> +    fprintf(stderr, "commandspath doesn't exist\n");
Why not specify the name of the file that the user is trying to read from?

2021-03-22 23:11 UTC, mpirvu commented on perf-tool/src/agent.cpp
> +
This new code needs to be indented.

2021-03-23 15:46 UTC, mpirvu approved these changes
LGTM

2021-03-23 15:46 UTC, merged