Add filtering capability to methodEnter/Exit events
eclipse/openj9-utils pull request #58
Opened 2021-03-22 22:17 UTC by mpirvu

Since methodEnter/Exit hooks can generate very many events
it may usefull to have some way of requesting such events
only for some classes/methods. This commit implements such
a filtering scheme.
Syntax of a command:
  {
    "functionality": "methodEntryEvents",
    "command": "start",
    "delay": 0,
    "stackTraceDepth": 3,
    "filter": {
       "class": "LMyThread;",
       "method": "syncRegion",
       "signature": "\\(I\\)"
    }

The matching for the "filter" class, method name and signature is
done using ECMAScript grammar: http://www.cplusplus.com/reference/regex/ECMAScript
Note that parenthesis must be escaped twice (using \\): once for
the JSON and one for regular expressions inside C++ code.
Square brackets and dollar sign which are typical used in Java class naming
also needs to be escaped.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

2021-03-22 22:23 UTC, mpirvu commented
@dsouzai Could you please review this PR? Thanks

2021-03-24 14:49 UTC, dsouzai requested changes
I may be wrong here, but if you have something like this:
```
{
"functionality": "methodEntryEvents",
"command": "start",
"delay": 0,
"stackTraceDepth": 3,
"filter": {
"class": "LMyThread;",
"method": "syncRegion",
"signature": "\(I\)"
}
}
...
{
"functionality": "methodEntryEvents",
"command": "stop"
}
...
{
"functionality": "methodEntryEvents",
"command": "start",
"delay": 0,
"stackTraceDepth": 3,
}
```
the second time we trace events, we'll still filter on the methods because the filter is only set if we see `filter` in the JSON. I think if `filter` is not set, the `regex`s should be reset (maybe only doing so if the various `bool`s are true)

2021-03-24 14:59 UTC, mpirvu commented
If filter is not present, then we send empty strings to `modifyMethodEntryEvents` in this code:
```
            std::string classFilter, methodFilter, signatureFilter;
            if (jCommand.contains("filter"))
            {
                auto jfilter = jCommand["filter"];
                classFilter = jfilter["class"].get<std::string>();
                methodFilter = jfilter["method"].get<std::string>();
                signatureFilter = jfilter["signature"].get<std::string>();
            }
            modifyMethodEntryEvents(function, command, sampleRate, stackTraceDepth, classFilter, methodFilter, signatureFilter);
```
The empty strings propagate to `methodEnterConfig.setFilter(classFilter, methodFilter, signatureFilter);`
and we end-up with an empty regex which matches everything (besides, the booleans that enable filetring are set to false:
```
void EventConfig::setFilter(const std::string& cls, const std::string& method, const std::string& sig)
{
    std::lock_guard<std::mutex> lg(configMutex);
    classFilter = !cls.empty();
    classRegex.assign(cls);
    methodFilter = !method.empty();
    methodRegex.assign(method);
    signatureFilter = !sig.empty();
    signatureRegex.assign(sig);
}
```

2021-03-24 15:01 UTC, dsouzai approved these changes

2021-03-24 15:01 UTC, merged